[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"


# テストファイルへのアクセスを許可
fs_permissions = [{ access = "read", path = "./test"}]


[rpc_endpoints]
astarzk = "https://rpc.startale.com/astar-zkevm"
astar = "https://evm.astar.network"